definitions:
  main.Job:
    properties:
      description:
        type: string
      finished_at:
        type: string
      id:
        type: integer
      priority:
        type: integer
    type: object
info:
  contact: {}
paths:
  /jobs:
    get:
      consumes:
      - application/json
      description: Gets all jobs ordered by priority
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Job'
            type: array
      summary: Get all jobs
      tags:
      - Jobs
    post:
      consumes:
      - application/json
      description: Creates jobs
      parameters:
      - description: An array of Job descriptions
        in: body
        name: jobDescriptions
        required: true
        schema:
          items:
            type: string
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Job'
            type: array
      summary: Create jobs
      tags:
      - Jobs
  /jobs/{id}:
    patch:
      consumes:
      - application/json
      description: Updates a jobs priority
      parameters:
      - description: The id of the job being updated
        in: path
        name: id
        required: true
        type: integer
      - description: The new priority
        in: query
        name: priority
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Job'
      summary: Update job priority
      tags:
      - Jobs
swagger: "2.0"
